### ISSUE TITLE
Tutorial: Radius node output port?

### ISSUE THREAD

**Issue by Gurkenglas** [luna/luna#101]
During the tutorial, I encounter:

![image](https://user-images.githubusercontent.com/1489801/35197471-db32c91a-fedf-11e7-817b-ef1ea5f64c80.png)

There is no explanation what an output port is and clicking around near and at the flashing area (the rounded orange square) does not do anything. After clicking `Next` to continue:

![image](https://user-images.githubusercontent.com/1489801/35197491-237c3d6e-fee0-11e7-8145-11cd989445e3.png)

The new node has disappeared, a line from the radius (output port, I suppose) follows the cursor, and it's still telling me to `Please wait...` as I type this.

**Comment by ricardopieper** [comment]
Duplicated:https://github.com/luna/luna-studio/issues/737, also wrong repo. 
I see you've opened many issues for Luna Studio and not the Luna Compiler. Do you know if you can move them?

**Comment by wdanilo** [comment]
There is a "move issue" button on the right. We try to move issues around, however, the author is also allowed to do so! 

@ricardopieper thank you for your help! Closing it as duplicate.

**Comment by Gurkenglas** [comment]
I'll close this and move the others.

**Comment by Gurkenglas** [comment]
I see no such button:

![image](https://user-images.githubusercontent.com/1489801/35198042-26da7f6c-fee9-11e7-8681-bfb5dead28e1.png)

**Comment by wdanilo** [comment]
Oh! I just realized it is a ZenHub feature, not built into GitHub. We use ZenHub internally, if you want, you can install free Chrome plugin or create online ZenHub account and you will get the button on the right below `1 participant` message !
