### ISSUE TITLE
MacOS Homebrew installation

### ISSUE THREAD

**Issue by HofmannZ** [luna/luna#107]
Hi,

Is there a official Homebrew of Caskroom installation setup? If not; would love to see one.

**Comment by kustosz** [comment]
Hey!
We have not considered this yet, but it may be useful. If there's anyone interested in contributing this, this is a great first issue to tackle.

**Comment by Cloud887** [comment]
Apt install would also be a fantastic addition...

**Comment by HofmannZ** [comment]
I'll write a PR to [homebrew-cask](https://github.com/caskroom/homebrew-cask) today.

**Comment by iamrecursion** [comment]
@HofmannZ Any updates on this?

**Comment by HofmannZ** [comment]
Someone beat me to it: [#42912](https://github.com/caskroom/homebrew-cask/pull/42912).

**Comment by iamrecursion** [comment]
That's not yet merged, but that appears to mean we're good on this side! Thanks for your interest, even if you were beaten to the punch! 👍
