### ISSUE TITLE
Do you have a plans to build web front-end for Luna?

### ISSUE THREAD

**Issue by salmazov** [luna/luna#113]
Hello!

I use c9.io environment and I work on many laptops/pc/macs with internet connection :) I have Heroku and VPS's.

It would be great if Luna have web ui (front-end) experience to use it only with Web Browser.

As you use Atom editor (Electron based), this is web techs (of course), I think it's not be so difficult to release Luna with browser support (it's my assumption).

**Comment by kustosz** [comment]
We do, yes! In fact, providing a Luna as a Service experience in the browser is one of the most surefire paths for our further development :)

I'll be closing this issue, as this isn't really an issue to be solved. In case you'd like to discuss this further, let's head over to our forum at https://discuss.luna-lang.org

**Comment by salmazov** [comment]
Thank you!
