### ISSUE TITLE
Erroneously placed markers break code

### ISSUE THREAD

**Issue by akavel** [luna/luna#125]
With the following code, on node `parseRaw1` I'm getting an error:

    Runtime error: Can't find function acc

while I'd expect this should work OK and return either `Empty` or a `List` with 1 element `"<"`:

```
«6»def parseRaw char ac«8»c: «11»case char of
    "<": Prepend "<" acc
    other: acc

«0»def main:
    «4»acce = Empty
    «3»char = "<"
    «5»prepend2 = Prepend char acce
    «2»prepend1 = Prepend "<" Empty«1»
    «10»parseRaw1 = parseRaw "<" Empty
    None
### META {"metas":[{"marker":11,"meta":{"_displayResult":false,"_selectedVisualizer":null,"_position":{"fromPosition":{"_vector2_y":0,"_vector2_x":0}}}},{"marker":4,"meta":{"_displayResult":false,"_selectedVisualizer":["base: json","base/json/json.html"],"_position":{"fromPosition":{"_vector2_y":-16,"_vector2_x":-592}}}},{"marker":3,"meta":{"_displayResult":false,"_selectedVisualizer":["base: json","base/json/json.html"],"_position":{"fromPosition":{"_vector2_y":-128,"_vector2_x":-576}}}},{"marker":5,"meta":{"_displayResult":false,"_selectedVisualizer":["base: json","base/json/json.html"],"_position":{"fromPosition":{"_vector2_y":-80,"_vector2_x":-352}}}},{"marker":2,"meta":{"_displayResult":false,"_selectedVisualizer":["base: json","base/json/json.html"],"_position":{"fromPosition":{"_vector2_y":-208,"_vector2_x":-16}}}},{"marker":10,"meta":{"_displayResult":false,"_selectedVisualizer":null,"_position":{"fromPosition":{"_vector2_y":-208,"_vector2_x":224}}}}]}
```

**Comment by kustosz** [comment]
Thanks for the report! That's a known lexer issue. Something wen't wrong then you were creating the code and a node marker got inserted in the middle of variable name. We'll be fixing that on both ends – i.e. ensuring that the markers do not get in the middle of variables and then if they do, that the lexer cuts them out.

The immediate fix I can suggest is to open the file with a non-luna-studio editor and manually remove the `«8»` marker  from the middle of `acc` argument. Sorry for this, getting code edits right is still tricky sometimes.

**Comment by akavel** [comment]
After removing the `«8»`, the code seems to never get past the typechecking phase for me :cry:  no types displayed anywhere in the project (and I restarted luna-studio just to make sure it loads from disk with no trash in memory). Should I open a separate issue for this? Or is a similar problem already reported in some existing issue?

**Comment by kustosz** [comment]
Oh, that's another issue, and one deserving a separate ticket. I think we don't handle pattern matching on strings properly, so the typechecker just dies. Please try rewriting the first function as: 
```if char == "<" then Prepend "<" acc else acc```
I don't know how have we forgotten about this, will fix soon.

**Comment by akavel** [comment]
Opened #126 for the `case` issue.

**Comment by mikusp** [comment]
Closing in favor of luna/luna-studio#448
