### ISSUE TITLE
Pattern matching on strings defeats typechecker

### ISSUE THREAD

**Issue by akavel** [luna/luna#126]
Per https://github.com/luna/luna/issues/125#issuecomment-365683922:

> [It appears] we don't handle pattern matching on strings properly, so the typechecker just dies. 

Code like in the snippet below:

```
«6»def parseRaw char acc: «11»case char of
    "<": Prepend "<" acc
    other: acc

«0»def main:
    «10»parseRaw1 = parseRaw "<" Empty
    None
```

doesn't seem to get past the typechecker phase (over 2 hours with no result).

Suggested replacement like below correctly gets through the typechecker:
```
«2»def parseRaw char acc:
    «3»if char == "<" then Prepend "<" acc else acc

«0»def main:
    «4»result1 = parseRaw "<" Empty
    None### META {"metas":[{"marker":4,"meta":{"_displayResult":false,"_selectedVisualizer":["base: json","base\\json\\json.html"],"_position":{"fromPosition":{"_vector2_y":0,"_vector2_x":176}}}},{"marker":3,"meta":{"_displayResult":false,"_selectedVisualizer":null,"_position":{"fromPosition":{"_vector2_y":0,"_vector2_x":0}}}}]}
```
but I want to use `case`, because I need to add more cases than two, then not that easy to replace with `if`.

**Comment by kustosz** [comment]
Should be resolved once https://github.com/luna/luna/pull/133 lands in master.

**Comment by akavel** [comment]
Confirming it works for me in 1.1.0.1, thanks! :grinning:
