### ISSUE TITLE
mainPath in shell/src/Luna/Shell.hs should not use getCurrentDirectory

### ISSUE THREAD

**Issue by Spaceghost** [luna/luna#139]
## What I thought would happen:
I should be able to run `luna` from anywhere and pass a path to be used for the `mainPath`.

## What actually happens:
Currently, the `luna` executable assumes that your current working directory is the top-level of a luna project directory.

### Root cause
https://github.com/luna/luna/blob/a6d2654305f6255550ab95c27d3a42341f5cc64b/shell/src/Luna/Shell.hs#L134

This has been present since:
 https://github.com/luna/luna/blob/9cfd850e16736f83a316a3b1a3930ef8b35ade91/shell/src/Luna/Shell.hs#L69

## What I expect to happen:
- No args
This should detect if the current directory is a Luna project or has a `Main.luna`

- filepath arg
If the file name is Main.luna, use that, if it's not, can we run the file if it defines a `main` function at the top level or something?

- dirpath arg
If the directory is a luna project or has a `Main.luna`, run it.

**Comment by Spaceghost** [comment]
Solving this for me will possibly solve #123 if done elegantly.

**Comment by kustosz** [comment]
This is now handled by the `PROJECT_DIR` env variable. A better interface will arrive with Luna 2.0. Closing for now.
