### ISSUE TITLE
Implement HTML Documentation Generator

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#171]
Luna Build provides the ability to generate HTML documentation from the source files. 

- [ ] Can parse the generated AST.
- [ ] Handles the new syntax (#144) 
- [ ] Generates HTML documentation.

**Comment by piotrMocz** [comment]
This issue is... Done? @wdanilo @lgawlik

**Comment by piotrMocz** [comment]
Oh, this is a duplicate of https://github.com/luna/luna/issues/302 -- I created #302 to accomodate the PR, because it wasn't connected anywhere. Please connect your PRs ;)
