### ISSUE TITLE
Parser for New Doc-Comment Syntax

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#174]
A parser needs to be implemented for the markup syntax in Luna documentation comments. 

```
# A brief summary of what my function does.
# 
# Some more detail on what the function does. This can span multiple lines, and
# these will be automatically concatenated as long as I don't leave a
# 
# blank line.
# 
# Block Heading
#   This is a block, and here I can talk about whatever is important to the 
#   block. In here I have a numbered list:
#     - First Number
#     - Second Number
#
#   But within the same block I can also have a bulleted list:
#     * First bullet
#     * Second Bullet
#       * Bulleted sub-list, but you can mix numbers and bullets.
# 
# Sometimes I might want to embed a code block in my documentation as a usage
# example. I can do this as `frobnicate foo bar`, but for bigger blocks I can:
#
#   > import Math
#   > frobnicate "a" (Math.sqrt b)
# 
# `a`: Here I'm making an item reference to the first function argument.
# `b`: Here I describe the second. 
#
# `return`: Here I can talk about the return value of the function.
# 
# You can find more information about doc comments in Luna by following this 
# [link -> https://luna-lang.gitbooks.io/docs/].

def frobnicate :: a -> Int -> Text
def frobnicate a b:
    ...
```

- [ ] Should parse `TODO`, `FIXME`, and `BUG` as special keywords.
- [ ] Formalise the comment spec.
- [ ] Should obey the above grammar.
- [ ] Documentation comments are associated with the line above which they are located.

**Comment by iamrecursion** [comment]
I'm starting to change my mind about not using Markdown. Many languages including Idris and Rust seem to be standardising on markdown with extensions for their documentation comments.

**Comment by wdanilo** [comment]
I don't see any advantages here. We can have the same `doctests` functionality here. Moreover, we would like to transpile to MarkDown to display the docs somewhere, so I'd rather look at docs commentso nly from perspective how they integrate with Luna and how they look like. Markdown has too many downsides for me, including tons of ways of declaring the same, lack of structural view (planned doc comments have nested structures indicated by indentaion) and some features we just dont watn to have, like tables. Moreover, we would need to extend it with our things, so again, we would need to transpile it to "standard" markdown to use its tooling.
