### ISSUE TITLE
Safe/Unsafe FFI Semantics

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#179]
Opening up some bikeshedding on the names for our safety annotations in Luna. The parser currently deals with the following:

- `safe`: The FFI call can be executed on any thread.
- `unsafe`: The FFI call must be executed on one thread.

Chatting has also proposed `moveable` and `pinned` respectively, which I like a lot. 

I will implement whatever changes to the parser are necessary based on the results of the discussion here.

**Comment by mwu-tow** [comment]
(This post is rather about semantics than names — but for better visibility/structure I decided to post it here. Please let me know if such discussions are better suited for the chat.)

I'm not sure what exactly is executing a FFI call in "one thread". Does it mean that the runtime maintains a single system thread that will be used for all FFI calls marked as unsafe? In such case it will be impossible to have any kind of parallelism between unsafe FFI calls and might be quite costly (calls requiring context switch and synchronization). It is surprising that `unsafe` is slower than `safe`. Why would anyone use `unsafe` then?

Also, what problem are we trying to solve with the keywords in the first place? Why do we want to mark functions as `safe` or `unsafe`? Is it really property of a function? Perhaps it is the particular IO action that should be marked as safe (as in "executed by a single OS thread" —> all FFI calls made when evaluating this action will be "safe")? 

Also, what problem are we trying to solve with the keywords in the first place? Why do we want to mark functions as `safe` or `unsafe`? Is it really property of a function? Perhaps it is the particular IO action that should be marked as [un]safe (meaning that all FFI calls made when evaluating this action will be "[un]safe")? 

Does Luna have any notion of thread? Can code be executed concurrently? What is the model for that? It is hard to talk about safe/unsafe semantics when little is known about the program execution model.

For example, if Luna allowed any kind of concurrency in its code, the proposed `safe` semantics might backfire. Consider the following code (sequence of two FFI calls):

```
	srand seed # FFI: set the seed
	rand # FFI: obtain the number (intention: based on the seed above)
```

where `srand` and `rand` are thread-local-state-based pseudo-random generator. Now, even if all srand/rand calls are mapped to a single os-thread, it might yield surprising results when two pieces of such code are evaluated concurrently. You might end up with the following FFI calls: `srand`, `srand`, `rand`, `rand`. It not the FFI function that needs to be called from a single thread. It is the IO action that uses it that needs to be bound. 

I don't like `moveable` and `pinned` as keywords as the first thing they make me think about is memory location of object (pinning as in preventing object from being moved by GC in memory). The function doesn't change its place.

**Comment by iamrecursion** [comment]
Naming aside, the whole point of this discussion is to come up with a way to deal with the issue of C functions utilising thread-local state. 

I do like the idea of batching computations under an IO action that guarantees all of those calls are run in a single thread. That could combine with the import-level safety annotations quite nicely. 

In our chat yesterday, @wdanilo proposed an interesting idea of (at some runtime cost) marking some FFI calls to have thread-local state stored and restored by the runtime itself if needed.

**Comment by mwu-tow** [comment]
The main question I raise is whether import-level annotations are needed at all? Having them without being able to bound an action to os-thread is not enough. However, being able to bind actions to threads should satisfy all use-cases I can think of right now.

The safe/unsafe annotations seemingly comes from Haskell but AFAIK the purpose was totally different, unrelated to thread-localness. `safe` was to allow long FFI calls without blocking the whole runtime under the single-threaded model. The safe/unsafe model seems to be largely obsoleted by being able to use `-threaded` runtime. Or, otherwise, if your runtime is single threaded, then you don't have issues with thread-local storage anyway.

**Comment by iamrecursion** [comment]
Perhaps that's true! The syntax is in the parser and working anyway, so I'm not going to remove it quite yet. While the names of our `safe` and `unsafe` were inspired by Haskell, the actual semantics thereof were not! 

I'm very much in favour of the notion of binding actions to threads, but how we actually do this needs some input from @wdanilo and @kustosz as to whether it can be done simply in Luna or requires more extensive changes. :)
