### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna#182]

**Comment by wdanilo** [comment]
<img width="635" alt="Enso Partnership" src="https://user-images.githubusercontent.com/1623053/125209007-483f1e80-e296-11eb-8040-c3c2da37b575.png">
<img width="635" alt="Enso School" src="https://user-images.githubusercontent.com/1623053/125209009-4aa17880-e296-11eb-930d-8f07b8c114b0.png">
