### ISSUE TITLE
Compiler freezes in Luna Studio due to strings after binary numbers

### ISSUE THREAD

**Issue by KyleHerndon** [luna/luna#184]
```
def main:
    hello = 0x1
    None
```
works as anticipated.
Changing this to 
```
def main:
    hello = 0x1b
    None
```
maintains the previous output before freezing. Any changes to the code will no longer update in the visualizer.

It appears that this works for any binary number and any string that immediately follows it.

Tested on both 1.2 and 1.2.1 in Luna Studio on Linux.

**Comment by iamrecursion** [comment]
Looks like this one is @kustosz's department!

**Comment by iamrecursion** [comment]
This appears to be fixed now.
