### ISSUE TITLE
Disable Comment Node Connection Semantics 

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#185]
As part of making this more functional, Luna performs some automatic connection of nodes from input to output where possible. It operates based on the following guidelines:

1. Luna is an Object-Oriented language, and hence each node has a special 'self' port. This self port is used as part of the 'main-line' of processing, often made visually distinct in the graph. In text, this is a group of variables:

    ```
    a = foo1 ...
    b = a.foo2 ...
    c = b.foo3 ...
    d = c.foo4 ...
    ```

   In this case, disabling a node means 'take no further action', and hence we can safely connect the node chain. If `## c = b.foo ...` is disabled, it has the effect of `c = b`.

2. If we disable a line that does not bind variables, it does not have any special meaning. `## print "foo"`, for example, just makes this node non-executable.
3. When disabling a line that does not use the 'self' port, we connect the first-used variable through if the types would match. In other cases, we cannot make it work, and execution is halted. For example, if we have `## x = foo a b`, and the types of `x` and `a` are the same, there is an implicit creation of `x = a` so execution can continue.

**Comment by wdanilo** [comment]
Regarding point 3, we can even not check types atm. We can just connect to the first input and if types dont match we will get compile time error. In fact I believe this is the desired final behavior too.
