### ISSUE TITLE
Parser does not parse defs after an empty class correctly

### ISSUE THREAD

**Issue by kustosz** [luna/luna#19]
With this code:
```
class Foo:
    Foo Bool

def main:
    putStr "hello world!"
```
the function `main` is parsed as a method of class `Foo`, not a module-level definition. This is fixed when we add any methods inside `Foo` – this code parses correctly:
```
class Foo:
    Foo Bool
    def dummy: None

def main:
    putStr "hello world!"
```

**Comment by wdanilo** [comment]
Already fixed in new parser.
