### ISSUE TITLE
Installing Luna is braking my PATH variable on Windows 10

### ISSUE THREAD

**Issue by varosi** [luna/luna#209]
Installing Luna 1.3 (upgrade from previous one) broke my user's PATH variable on Windows 10.
My PATH is long and may be the problem is that Luna installer may not handle correctly long Windows environment variables.

**Comment by wdanilo** [comment]
@varosi Could you provide more information about it? What does it mean it broke the PATH? What happened to id? Btw @sylwiabr please take lead here for future questions and discovery what happens.
