### ISSUE TITLE
`Non-exhaustive patterns in case` error

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#210]
for code in luna:
```
class MyClass:
    MyClass
    MyClassVal:
        a:: Int
        b:: Text
    def a: case self of
        a _: a
```
error is `luna: src/Luna/Pass/Transform/Desugaring/PatternTransformation.hs:(40,45)-(46,30): Non-exhaustive patterns in case`

**Comment by wdanilo** [comment]
Non-exhaustive pattern should never appear, so its a bug, however the code is invalid. The case match pattern `a _` is invalid. You cannot match on a variable with its field. It just do not make sense. You can pattern match on a constructor and its fields like `Vector _ _ _` OR you can pattern match on a variable `a`, but you cannot deconstruct a variable-like constructor.

**Comment by sylwiabr** [comment]
I know that code is invalid and I know how to fix it. It should just be a luna error nat invalid pattern match from Haskell  @wdanilo
