### ISSUE TITLE
`.DS_Store` file in luna project causes an error

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#211]
```
~/luna/projects/DummyProject/local_libs/.DS_Store/src/:~/luna/projects/DummyProject/local_libs/.DS_Store/src/: getSymbolicLinkStatus: inappropriate type (Not a directory)
```

**Comment by iamrecursion** [comment]
Can't currently repro. Waiting for a repro case from @sylwiabr.

**Comment by piotrMocz** [comment]
I have been successfully opening projects with `.DS_Store` inside and I cannot reproduce this -- closing.

@sylwiabr if this problem persists, feel free to re-open. If you can provide a repro scenario, that would be awesome.
