### ISSUE TITLE
Managed Pointers release too early

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#212]
In OpenCV example for bigger (2 mb jpg) images the ManagedPointer for class Mat is released too early which causes the OpenCV library crash.

**Comment by wdanilo** [comment]
@mikusp Michal had problems with exactly this bug recently. What is the estimation time needed to fix it on your side?

**Comment by kustosz** [comment]
We need to revise the implementation anyway. I wouldn't close this, as this issue has occured previously in different projects, so it need investigating anyway.
