### ISSUE TITLE
Function unexpectedly not getting evaluated

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna#218]
Hello,
consider the following code:
```
import Std.Base

def baz:
    print "baz"

class Foo:
    def bar:
        print "bar1"
        baz
        print "bar2"

def main:
    Foo.bar
```

The output is
```
Running main...
bar1
bar2
main finished
```

I find it unexpected that my custom function `baz` is not evaluated even when `print` calls before and after are.

**Comment by mwu-tow** [comment]
Actually even simpler 
```
import Std.Base

def baz:
    print "baz"

def main:
    print "bar1"
    baz
    print "bar2"
``` 
behaves in the same way.

**Comment by wdanilo** [comment]
@kustosz do you know what's happening here? This is clearly improper behavior. If its a bug in every Luna version (not only Michal's) I'm totally astonished nobody found it before.

**Comment by kustosz** [comment]
I do :( I think I introduced it rather recently, when fixing another, similiar bug. I'm implementing correct solution in the new interpreter.

**Comment by wdanilo** [comment]
Glad to hear that! We need to cover luna with high level tests soon, our micro-tests do not catch such bugs.

**Comment by kustosz** [comment]
@mwu-tow workaround for now: replace `baz` with `_ = baz`. Real fix coming with the new Luna in ~2 weeks.

**Comment by mwu-tow** [comment]
The issue seems to be fixed in the current https://github.com/luna/luna-core :)

**Comment by kustosz** [comment]
Perfect! :)
