### ISSUE TITLE
lookupSymbol fails to find library when .dll extension is explicitly given

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna#220]
Consider the following code:
```
import Std.Foreign

def main:
    lookupSymbol "libmongoc-1.0.dll" "mongoc_init"
```

I have `libmongoc-1.0.dll` present under `PATH`.

It fails with the following output:
```
Running main...
Luna encountered runtime error: Native library libmongoc-1.0.dll could not be loaded. Details:

loading "liblibmongoc-1.0.dll.dll" failed with: LoadLibrary: invalid argument (Nie można odnaleźć określonego modułu.)
loading "libmongoc-1.0.dll.dll" failed with: LoadLibrary: invalid argument (Nie można odnaleźć określonego modułu.)
loading "native_libs\windows\liblibmongoc-1.0.dll.dll" failed with: LoadLibrary: invalid argument (Nie można odnaleźć określonego modułu.)
loading "native_libs\windows\libmongoc-1.0.dll.dll" failed with: LoadLibrary: invalid argument (Nie można odnaleźć określonego modułu.)
```

It seems that .dll extension is appended even if explicitly specified and the library cannot be found. If I remove the extension and look just for `libmongoc-1.0` everything is fine.

The issue isn't serious but it surprised me, as I expected function to have similar behavior as WinAPI's `LoadLibrary` (that is conventionally called with full filename).

**Comment by sylwiabr** [comment]
@mwu-tow does it work with the new Luna build?

**Comment by mwu-tow** [comment]
Yes, I just confirmed that issue is fixed. Thanks!
