### ISSUE TITLE
Runtime error - Luna 1.3.0.8

### ISSUE THREAD

**Issue by BinarySoftware** [luna/luna#225]
![issue-runtime_error](https://user-images.githubusercontent.com/26655166/42317726-56053896-804d-11e8-95fa-c35fe03980c4.png)
 Error when running penCV Example in Luna on Windows

**Comment by mikusp** [comment]
Tested with OpenCV branch newcore and pacakge 1.3.0.16

**Comment by sylwiabr** [comment]
should work since LunaStudio 1.4
