### ISSUE TITLE
Standard library not found

### ISSUE THREAD

**Issue by ad-si** [luna/luna#226]
When I try to compile my project I get following error:

```
Standard library not found. Set the LUNA_LIBS_PATH environment variable
```

How can this be fixed?

**Comment by iamrecursion** [comment]
All you need to do is just what it suggests! If you take a look at the [Running Luna](https://github.com/luna/luna/blob/master/README.md#running-luna) section of the `README.md` it mentions where you can find the path to set the environment variable to. Let me know if that helps!

**Comment by kustosz** [comment]
Except the readme seems outdated! It's `LUNA_LIBS_PATH`, not `LUNA_HOME` now :)

**Comment by iamrecursion** [comment]
I am apparently blind! I'll get that fixed ASAP.

**Comment by ad-si** [comment]
Yes, that fixed it. I had set `LUNA_HOME` as described in the Readme 😉
