### ISSUE TITLE
Non-deterministic compiler crash: REDIRECTION LOOKUP ERROR

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna#233]
The issue happens with 70%-80% rate when I compile this commit: luna/Dataframes@47dcfae8c79db50ca6aacba38e2ea84999e28be5

The compiler output:
```
REDIRECTION LOOKUP ERROR. Layer = Users. Key = Ptr 0x0000000040058739 ComponentSet SmallVector (Struct (Ptr 0x000000003e229858))
CallStack (from HasCallStack):
  error, called at src\Data\Graph\Store\Buffer.hs:406:29 in luna-core-0.0.6-KXqSFKEg6V68ry8VvH8qpT:Data.Graph.Store.Buffer
```

I have failed in my attempt to reduce — stripping seemingly unnecessary code causes issue to go away.
Code is likely invalid anyway — when REDIRECTION LOOKUP ERROR doesn't show up, it fails with 
```
CompileError {_contents = "Cannot unify Std.Base.Maybe Std.Base.Text with Std.Base.Int.", _arisingFrom = [], _failedAt = [Function (Qualified "Dataframes.Main") "main",Method (Qualified "Dataframes.Internal.Test.Test") "TestArrayBuilder" "run",Method (Qualified "Dataframes.Internal.Test.Test") "TestArrayBuilder" "testColumn"]}
```

**Comment by mwu-tow** [comment]
I just got it on 1820a2dcff258c04c7f09b259401f4078a4c6e4d
It happens very rarely though.

**Comment by iamrecursion** [comment]
Just to clarify it happens during compilation of `luna` itself?

**Comment by mwu-tow** [comment]
No, this happens when calling `luna` to execute my program. Usually some code using Dataframes.

**Comment by iamrecursion** [comment]
Probably a bug in IR then.
