### ISSUE TITLE
luna-shell sometimes fails to compile on Windows

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna#236]
When I run `stack build luna-shell` on luna/luna-core repo for a first time, I get:
```
luna-shell-1.2: configure (lib + exe)
Configuring luna-shell-1.2...
luna-shell-1.2: build (lib + exe)
Preprocessing library for luna-shell-1.2..
Building library for luna-shell-1.2..
[1 of 5] Compiling Luna.Shell.CWD   ( src\Luna\Shell\CWD.hs, .stack-work\dist\7d103d30\build\Luna\Shell\CWD.o )
[2 of 5] Compiling Luna.Shell.Interpret ( src\Luna\Shell\Interpret.hs, .stack-work\dist\7d103d30\build\Luna\Shell\Interpret.o )
[3 of 5] Compiling Luna.Shell.Command ( src\Luna\Shell\Command.hs, .stack-work\dist\7d103d30\build\Luna\Shell\Command.o )
ghc.EXE: internal error: IMAGE_REL_AMD64_ADDR32[NB]: High bits are set in 244506561 for ghczmprim_GHCziTypes_ZMZN_closure
    (GHC version 8.4.2 for x86_64_unknown_mingw32)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
Completed 2 action(s).

--  While building package luna-shell-1.2 using:
      C:\s\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.2.0.1_ghc-8.4.2.exe --builddir=.stack-work\dist\7d103d30 build lib:luna-shell exe:luna --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 3
```

If I run then command again, the build succeeds.
I guess it might be related with TH memory usage — https://ghc.haskell.org/trac/ghc/ticket/13112 — as suggested in similar issue: https://github.com/haskell-tools/haskell-tools/issues/277

**Comment by wdanilo** [comment]
@mwu-tow could you please link it (describe the connection) in related GHC trac issue? This is definitely not our bug and we could not do much with it.

**Comment by iamrecursion** [comment]
Does it always happen in `Luna.Shell.Command`?

**Comment by mikusp** [comment]
Could you try whether using `-fexternal-interpreter` GHC option helps and/or upgrading GHC version to 8.4.3? You'll probably need to bump LTS version in stack.yaml

**Comment by mwu-tow** [comment]
@iamrecursion It happens iff `Luna.Shell.Command` is built after `Luna.Shell.Interpret` by the same GHC process. I'd expect the issue lies with `Interpret`, as it takes ~10GB to compile. I'm not sure why it didn't come out in #231, perhaps I missed it.

**Comment by iamrecursion** [comment]
It doesn’t surprise me that `Interpreter` results in high memory usage. It pulls in a lot of the code that uses type families and will be incurring the same penalties as the rest of the codebase.

I don;’t know if there are ways to reduce it, but we’ll definitely look into it as part of the optimisation work.

**Comment by mwu-tow** [comment]
@iamrecursion Another thing that puzzles me is why sequentially compiling several modules causes the issue but compiling them one by one succeeds. It looks as if there was a severe memory leak in GHC.

@mikusp The GHC option `-fexternal-interpreter` does help. GHC 8.4.3 doesn't help. (but took more than two hours and one hard machine reset before failing…)

**Comment by iamrecursion** [comment]
I don’t know, honestly! I think it’s a GHC problem not ours.

**Comment by iamrecursion** [comment]
This is a GHC issue, not ours. Closing.
