### ISSUE TITLE
MacOs installer fails when running under a non-admin user

### ISSUE THREAD

**Issue by RR2DO2** [luna/luna#238]
The installer is trying to write to /Applications/LunaStudio.app/ without prompting for elevation. This results in the following error:

/Applications/LunaStudio.app/: createTree: permission denied (Permission denied)

This is on High Sierra, lunainstaller for beta 1.4

**Comment by iamrecursion** [comment]
Issue moved to [luna/luna-studio #1037](https://github.com/luna/luna-studio/issues/1037) via [**ZenHub**](https://www.zenhub.com/)
