### ISSUE TITLE
Improving Compilation Time and Memory Usage - GHC TF Patch

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#240]
Currently the compilation performance for Luna is absolutely _abysmal_, requiring exceedingly large amounts of memory and significant time to compile with optimisations. The is due to our heavy use of type-families, which have awful compilation performance in GHC.

There is a [patch](https://ghc.haskell.org/trac/ghc/ticket/8095) for GHC which aims to alleviate this problem somewhat, but it currently is out of date and will not apply on either `master` or `ghc-8.6`. I have [commented](https://ghc.haskell.org/trac/ghc/ticket/8095#comment:51) on the Trac ticket to register our interest, but improving this is currently blocked waiting on a response from the GHC developers.

**Comment by iamrecursion** [comment]
This has just had an [update](https://ghc.haskell.org/trac/ghc/ticket/8095#comment:56) from Ben Gamari (author of the patch), which states that he aims to get the patch into ghc-8.8.

**Comment by piotrMocz** [comment]
This task feels kind of "Iceboxy" or "Backloggy" -- the flow we have right now assumes that "Blocked" means "Blocked by one of our tasks" (and I'm moving this cause we need to stick to the WIP limits: please ask @lgawlik for motivation if you're interested).
