### ISSUE TITLE
Parser incorrectly parses two functions when one of them is invalid

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#242]
@mikusp commented on [Fri Jul 27 2018](https://github.com/luna/luna-core/issues/128)

Consider code:
```
import Std.Base
def foof:
«0»def main:
    «1»4
```

When parsed, I would expect to see a Record with two elements, one Marked, containing `main` function and one Function containing invalid `foof` function. However, what is returned, looks like this:
![zrzut ekranu z 2018-07-27 12-03-45](https://user-images.githubusercontent.com/2052578/43315204-8b544d4e-9195-11e8-82e1-14ddbc641f16.png)
Both functions are considered to be without markers. Furthermore, when our marking code runs, it will put a marker for foof, right before def (as expected) AND for main, but right after `foof`! Resulting code looks like this:
```
import Std.Base
«2»def foof«3»:
«0»def main:
    «1»4
```
completely breaking our double representation.

**Comment by wdanilo** [comment]
Fixed in new parser
