### ISSUE TITLE
Graceful parser errors

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#243]
@sylwiabr commented on [Thu Jul 26 2018](https://github.com/luna/luna-core/issues/125)

a code like:
```
def main:
    a = 12
        b = 13
    None
```
will end up with an error like:
![obraz](https://user-images.githubusercontent.com/12892578/43259828-eaf60b7a-90d7-11e8-9a96-a54d76f28834.png)
impossible to scale/copy or read

**Comment by wdanilo** [comment]
Already fixed in new parser.
