### ISSUE TITLE
Create pretty printer for field setting terms

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#249]
@kustosz commented on [Sun Jul 22 2018](https://github.com/luna/luna-core/issues/118)

They are not currently supported. This leads to the parser test suite failing and errors in Luna Studio.

**Comment by wdanilo** [comment]
What are field setting terms? Can I see an example code?

**Comment by lgawlik** [comment]
@iamrecursion could you please answer Wojtek?

**Comment by iamrecursion** [comment]
This is something for @kustosz to answer. The issue is only owned by me because I transferred it from the `luna-core` repo when that switch was made.
