### ISSUE TITLE
Make the Interpreter Strict

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#252]
Currently the runtime module is not using `-XStrict` and relies on lazy behaviour in places. As the start to improving the runtime performance of Luna we want to make this module strict. 

- [x] Enable `-XStrict` for the entire module.
- [x] Re-introduce use of laziness where relevant.

**Comment by mikusp** [comment]
I tried putting Strict in some files, and was not impressed by the results. I think that strictness somehow resulted in compiling much more code of stdlib than it was required, as RAM usage of `luna` skyrocketed.

**Comment by iamrecursion** [comment]
I’ll definitely have to investigate that. There are some places where laziness is used, so it’s not a wholesale bandage.
