### ISSUE TITLE
System Library Management

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#275]
### Summary
Currently when installing Luna Packages, either as part of Luna Studio or via Luna Build in the future, there is no way for Luna to manage system dependencies that these packages might depend on. As a result, the `luna-package` library should provide API to automatically install system libraries locally when required.

Current work towards implementing this task can be found on the [package-deps](https://github.com/luna/luna/tree/package-deps) branch. 

### Value
Currently, users of Luna's libraries find themselves needing to install significant numbers of system-dependencies using their system package manager in order to have the Luna libraries work. This isn't a brilliant state of affairs, and so adding this functionality would both:

- Allow Luna Studio to ensure that all system dependencies are installed for the bundled libraries.
- Allow future uses of `luna install ...` to have any system dependencies installed automatically.

### Specification

- [ ] Uses [Nix](https://github.com/NixOS/nix) to install and manage system libraries on *nix and MacOS (`Luna.Package.Dependency.System.Unix`).
- [ ] Has a design for a solution for system library management in the source. (`Luna.Package.Dependency.System.Windows`). 
- [ ] Provides a _transparent_ API to users based on [hnix](https://github.com/haskell-nix/hnix) or calling out to the Nix executable. 
- [ ] This API takes just a list of package names for the _system dependencies_. 
- [x] The package configuration contains a list of system _direct_ dependencies. 
- [ ] These system dependencies can be gathered from package configuration `.luna-package/config.yaml` (e.g. `installPackageDeps :: MonadIO m => Local.Config -> m Bool`). This machinery can later be used by Luna Build to install packages (`luna install ...`). 
- [ ] Provides a method for bundling nix for use by Luna (for both Luna and Luna Studio). 
- [ ] Nix can be installed without elevated privileges. 
- [ ] The use of Nix is hidden from the users as much as possible. 
- [ ] Provides libraries only in a sandbox. 
- [ ] New libraries should be available without process restart. 
- [ ] Should handle the transitive closure of system dependencies when given a list (auto via nix).
- [ ] Should handle the transitive closure of system dependencies when given a project. 

### Acceptance Criteria & Test Cases

- [ ] Nix can be successfully installed, on-demand, without the need for elevated privileges.
- [ ] System libraries can be read from a package's configuration and installed.
- [ ] The API supports installing a list of provided packages.
- [ ] This functionality is exercised in the HSpec test suite. 
- [ ] New libraries are available without restarting the luna process.

**Comment by iamrecursion** [comment]
#### Investigating Nix

- Nix provides for isolated environments that only have access to the required dependencies. This is great for supporting reproducible builds and sandboxing of dependencies.
- You can't make new libraries available to a nix shell without rebuilding the derivation, which doesn't help with the 'live reload' requirement. 
- The use of `nix-shell` to set up environments is quite limiting in the context of Luna, but perhaps forcing Nix to use a known location for the nix-store would be less limiting (`--store`).
- As nice as it would be to base Luna's build system on nix, I'm not sure it's feasible at this point in time.

Nix is, in some ways, artificially limited when it comes to making system-level dependencies easily available to luna programs. Even when using `nix run --store ...` or in a proot container we end up with no easy way to actually set up the dependencies for luna unless it, too, is run inside the container.

**Comment by iamrecursion** [comment]
#### NIx and Symlinking

When using nix with a user store (via `nix run --store`), we end up with a user-local nix store that we can use for management of system dependencies. This would allow the following flow:

1. Luna creates a nix store in `~/.luna/dependencies/` (which has an implicit `nix/` subfolder).
2. When acquiring dependencies for a package, drop into a user-shell and load the derivations for those dependencies.
3. Using these dependencies we can find them in the current shell environment, and acquire the actual locations within the nix store. 
4. We can symlink these dependencies into `package/.luna-package/deps/system/` and have that be the only place that Luna looks for system libraries (in addition to the `local-libs` folder in the project.

**Comment by iamrecursion** [comment]
#### Performance

- Nix's startup performance is not instant, meaning that we want to start nix as _little_ as possible. 
- Operating inside a pseudo-root of some kind _may_ involve a performance hit (e.g. proot uses ptrace to intercept syscalls, which results in a performance hit). I don't know if that applies to the nix-store sandbox, but I suspect it doesn't as it uses user-namespaces via the `unshare` syscall). 
- If we only start nix to acquire and link dependencies then we can avoid this on build as long as the dependencies haven't changed.

**Comment by iamrecursion** [comment]
#### UX
I have some user-experience concerns that stem from us using nix under the hood.

- It may be very difficult to provide useful status information to the user while nix is downloading things. I don't think that NIx's status information is _particularly_ good in any case, but as we'd be working at text-level there isn't much choice.
- If anything goes wrong on the nix end it's very hard for us to report accurate errors to the users.

**Comment by iamrecursion** [comment]
#### Static Builds of Nix

It is currently proving _very_ difficult to get a statically-linked build of Nix. Their makefile architecture is a touch opaque, making it difficult to work out where we can apply `-static` to the compiler and linker flags. 

Without a static build of Nix, we run into the same dependency issue we would be hoping for it to solve, but for Nix itself.

**Comment by iamrecursion** [comment]
#### Long-Term Feasibility

- While nix is seeing increasing adoption in certain parts of the software industry, it doesn't seem to have made any particularly big inroads into enterprise.
- Nix _is_ used in production, but I can't find much information as to the scale at which this is true.
- Nix is, however, known to be a stable tool, both in terms of a lack of bugs and the number of breaking changes made.

**Comment by iamrecursion** [comment]
#### Summary 2018-09-10
In addition to the above comments (all of which are up to date as of this post), the following notes apply:

- Even when bundling the `nix*` commands using `nix-bundle`, the resultant binaries have a dependency on the configuration of the system that the bundle is built on. An example of this is that the search paths are hardcoded: `warning: Nix search path entry '/home/ara/.nix-defexpr/channels/nixpkgs' does not exist, ignoring`. 
- This means that it seems that Nix is just _not_ relocatable. There may well be some things that I've missed, so I'm not yet comfortable declaring that it isn't, but my suspicions are tending in that direction.

If, however, we assume the presence of a working (sandboxed) Nix install, the following things become relevant:

- Nix, when used naively, is likely to provide a poor UX for our users. From my testing it seems unlikely that we can _mask_ the involvement of Nix, instead exposing some of the nix interface to users. 
- Using Nix in a basic fashion would mean that Luna has to be executed within a sandbox. I'm not sure what it means for the UX, but I'm uncomfortable pursuing this direction without a better idea of what it would mean for our users.
- If we _can_ have Nix working, then [symlinking](https://github.com/luna/luna/issues/275#issuecomment-419024214) seems like the most promising approach. This would allow for live detection of new dependencies, and a much better user-experience (as we control the whole toolchain).

**Comment by iamrecursion** [comment]
I'm in two minds about this at the moment, and I don't feel well-positioned enough to make a concrete recommendation. What follows are just my thoughts:

- Nix _does_ implement 90% of the functionality that we need with regards to management of system-dependencies. It provides sandboxing, a repository of prebuilt deps, and handles all the pathing messiness for us. 
- However, as far as I can see, using Nix would require us to make some compromises in order to force Nix to fit exactly what we need from it. 
- Implementing such functionality ourselves is a _very_ significant chunk of work however. 

I think that, currently, I am leaning towards implementing things ourselves, if only because it means we can create a solution better targeted at exactly what we need. This would also allow us _far_ more control over the UX of the tool, which I think is a big boon.

**Comment by wdanilo** [comment]
@iamrecursion thanks for the info. Could you clarify the following point for me please?

> Nix, when used naively, is likely to provide a poor UX for our users. From my testing it seems unlikely that we can mask the involvement of Nix, instead exposing some of the nix interface to users.

What are you referring here exactly to? What are the parts that we cannot hide from users?

Regarding running Luna in a sandbox - this is one of our key design decisions. We want Luna library authors to work in a sandox, so even if you have some libs in your system, they are not seen unless you provide special config. This way you would not develop a library that works on your system but breaks somewhere else due to missing deps. This implies that Luna should be run in such sandbox.

Moreover, does writing something from scratch involve all the crazy stuff nix has? I mean all the sandboxing techniques, user namespace support requirement, creating a store with dependencies and patching all linux libs to be compatible with it? If so, this is an incredible big task. We cannot assume here that we deliver to the users only a small amount of predefined libs. We would rather allow people to create new Luna libs with easy and just provide a simple configuration files enumerating what shared libs they want access to, so we should rather use some existing package provider, let it be rpm, deb, nix or portage.
