### ISSUE TITLE
Inconsistent type inference when connecting values to ports

### ISSUE THREAD

**Issue by joenash** [luna/luna#279]
Please ensure that you are running the latest version of Luna before reporting the bug! It may have been fixed since.

### General Summary

The order in which you connect ports has an effect on the type inference. For example, if you have a node whose expressions is `+`, you will have two input ports, `a0` and `a1`. If you connect an `Int` value to port `a0` first, the type of the node will change to `Int -> Int`. If you connect a value to `a1` first, the type will change to `a3 -> *`. The number of input ports also varies in each case: with `a0`, an input port disappears, leaving just one port. With `a1`, both ports remaining separate and distinct.

![2018-09-06 21 42 26](https://user-images.githubusercontent.com/1790822/45184095-d741a780-b21d-11e8-901a-29b4005d10d1.gif)

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Create a new project with `luna init MyProject`.
2. Enter the node editor.
3. Create a node with expression `+`.
4. Create an `Int` value node.
5. Connect that value first to `a0`.
6. Disconnect the value from `a0`.
7. Connect the value to `a1`.

### Expected Result

The order of port connection should not affect the result of type inference: in both cases, the type parameter should take the `Int` value. 

### Luna Version

1.4 beta

**Comment by wdanilo** [comment]
This is really strange. It seems like backend sending wrong info in the 2nd case. Moreover in the first case the inputs disappear and don't get colored. On my 1.4 it's working correctly.

**Comment by wdanilo** [comment]
This is the first case here:
![9](https://user-images.githubusercontent.com/1623053/45188584-3ced5e00-b235-11e8-9958-81ab35a4ea37.png)

**Comment by wdanilo** [comment]
And the second:
![9](https://user-images.githubusercontent.com/1623053/45188614-58f0ff80-b235-11e8-9a15-f9f9696c2ffa.png)

Seems like multiple bugs - in display and type inference.

**Comment by joenash** [comment]
This isn't a bug, it turns out to be inherent to how the standard library + is written. Thanks for the explanation @wdanilo  - it may prompt a future conversation about the complexity of the standard library for folks new to Luna, but for now, closing this out :sparkles:

**Comment by wdanilo** [comment]
Ok, @joenash sorry for the confusion, there are few bugs here. So the type inference works as expected (and that's good), but there are some serious UI issues. First of all in your screenshot, after you connect to the first input port the node has suddenly single port visible (the second is disappearing - this is a bug). On my second screenshot, there is also a display bug, so I'm re-opening this issue. I'm assigning here @pmlodawski. Piotrek, we have to be sure these errors are not available in the new GUI and then close this issue.

**Comment by pmlodawski** [comment]
I can confirm that it is backend/TC issue
