### ISSUE TITLE
Multiline list literals cause a parsing error

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna#28]
@piotrMocz commented on [Sun Aug 20 2017](https://github.com/luna/luna-studio/issues/216)

Say we have a datatype:
```
class Foo:
    a :: List Text
```
The following gives a parsing error:
```
def f:
    x = Foo [
        "ala",
        "ma",
        "kota"
    ]
    x
```
And the error says `Unexpected token: x`.

**Comment by wdanilo** [comment]
Already fixed in new parser
