### ISSUE TITLE
Port appearance and inference when connecting nodes

### ISSUE THREAD

**Issue by joenash** [luna/luna#280]
Please ensure that you are running the latest version of Luna before reporting the bug! It may have been fixed since.

### General Summary

When you connect a value to a node with multiple input ports, it sometimes results in a port disappearing, and remaining grey. When another node is moved, or deleted, the correct number will be visible, and will take on the correct type inference colour. 

![2018-09-06 21 47 04](https://user-images.githubusercontent.com/1790822/45184288-6f3f9100-b21e-11e8-967f-42bef1844362.gif)

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Create a new project with `luna init MyProject`.
2. Enter the node editor.
3. Create a node with expression `+`.
4. Create two `Int` value nodes.
5. Connect one value to port `a0`.
6. Observe that an input port disappears, leaving just one large grey input port.
7. Delete the second value node.
8. Observe that the input ports have once again split into two, and have taken on the `Int` inferred colour.

### Expected Result

Number of ports should not change when a node is connected. Type inference should not change when an unrelated node is deleted.

### Luna Version

1.4 beta

**Comment by joenash** [comment]
Little bit more on this bug, see the gif below for what happens when I try to connect to the second input port. 
![2018-09-07 11 57 36](https://user-images.githubusercontent.com/1790822/45215448-5f16c880-b295-11e8-85dd-02ff91cfaf9f.gif)

**Comment by joenash** [comment]
Noticed the inputs were grey after I joined both inputs: behaviour is the same as one input, remains grey until I create or delete another node

![2018-09-07 12 00 48](https://user-images.githubusercontent.com/1790822/45215561-be74d880-b295-11e8-943c-6dfc2fa164fa.gif)

**Comment by lgawlik** [comment]
Assigning @mikusp to verify if it is Backend bug and move it forward.

**Comment by mikusp** [comment]
I cannot reproduce these issues on Linux build

**Comment by lgawlik** [comment]
@piotrMocz please try to reproduce on Mac
