### ISSUE TITLE
Minor Monorepo

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#284]
### Summary
Currently people are developing Luna and its accompanying libraries in such a fashion that they are all developed together. Unfortunately, this can cause issues where changes are pushed to one repo (e.g. Luna), but not to others, resulting in the build breaking for everybody else. 

This issue proposes moving all of the libraries depended on by Luna (that we own and actively develop) into the `lib/` directory of the project. This will ensure that all changes should be pushed to the origin when people are developing things concurrently. 

While it is _nice_ to have these libraries on Hackage, it doesn't make sense to do so if we are constantly breaking things as a result. 

### Specification

- Libraries owned by the Luna project are moved into `lib/`. 
- Both `stack-local.yaml` and `config/snapshot-local.yaml` are to be removed.

**Comment by mikusp** [comment]
I think removal of config/snapshot-local.yaml and stack-local.yaml should also be included.

**Comment by iamrecursion** [comment]
That's a really good point. Thanks!

**Comment by piotrMocz** [comment]
Perfect, thank you so much! 💯 🥇 
Please run this by @wdanilo though ;)

**Comment by piotrMocz** [comment]
@iamrecursion I guess this can be closed, right?
