### ISSUE TITLE
Being able to convert JSON stream to JSON definition/object

### ISSUE THREAD

**Issue by TheOnlyArtz** [luna/luna#288]
Luna 1.4.101.1(latest according to 12 to september 2018)

### General Summary

Being able to convert a JSON stream to an actual JSON definition

### Motivation

 I'm trying to make some WebSocket stuff and I've encountered a problem where I can't really convert a JSON stream to a JSON definition/object

**Comment by mikusp** [comment]
This issue prevents from Luna Studio from showing visualizations for `Stream a`
