### ISSUE TITLE
Allow comments on constructors

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#297]
### General Summary

Docstrings above the constructors in classes are breaking the code. However we want to be able to write documentation for them so maybe parser should allow that.

### Motivation

Better and more detailed documentation.

**Comment by TheOnlyArtz** [comment]
Why not allowing comments everywhere in the first place?

**Comment by wdanilo** [comment]
Comments should never break code, so this is a serious bug. I'm changing its priority.

**Comment by wdanilo** [comment]
I'm not fixing it yet, as it requires re-writing comments handling. Currently commets are the only not general thing in parser and we need to handle them automatically everywhere and discard if not bound to a definition.

**Comment by sylwiabr** [comment]
It is not blocking. We just should remember about this and fix it at some point.
