### ISSUE TITLE
Curried chained method calls no longer work

### ISSUE THREAD

**Issue by kustosz** [luna/luna#301]
Please ensure that you are running the latest version of Luna before reporting the bug! It may have been fixed since.

### General Summary

In the 1.5 version of Luna (new parser) expressions like `.foo.bar` do not work properly, rendering most of my projects unusable. Expressions like `[1,2,3].each .succ.pred` parse to something like `[1,2,3].each (.succ).pred`, which results in type errors. This is a new behavior since 1.4 where things worked properly.

### Steps to Reproduce

Use an expression like `[1,2,3].each .succ.pred`. Results in type error about not being able to call a method on a function. Pretty printer shows it as `[1,2,3].each (.succ . pred)`, instead of `[1,2,3].each .succ.pred` how it used to be in 1.4.

### Expected Result

Same behavior as 1.4

### Actual Result

Broken semantics

### Luna Version
1.5

**Comment by piotrMocz** [comment]
Works ok ;)
