### ISSUE TITLE
Generate project documentation

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna#302]
This issue is retro-created to fit the pull request: https://github.com/luna/luna/pull/281
The reason is that ZenHub won't let me close the PR and move it to the `Acceptance` column.

**Comment by iamrecursion** [comment]
Should this issue now be closed?

**Comment by piotrMocz** [comment]
@iamrecursion yes. In Luna Studio I would wait for the feature to make it into a release package, but this is `luna`, so I'm closing it.
