### ISSUE TITLE
Discord module on Luna website does not behave well

### ISSUE THREAD

**Issue by Sygmei** [luna/luna#303]
### General Summary

Problem from the website, the discord widget does not behaves well when scrolling down

### Steps to Reproduce

Go to the luna website, scroll a bit, play with the discord module

### Actual Result

The discord module glitches and go behind one of the title : https://gfycat.com/ResponsibleForthrightCheetah

**Comment by iamrecursion** [comment]
Closed the wrong issue.

**Comment by ielm** [comment]
I can't find the website source, but adding `style="position: unset"` to `.header-container` seems to fix the issue on Chrome.

**Comment by iamrecursion** [comment]
Website is being redesigned.
