### ISSUE TITLE
Fix Renaming of Luna Packages Across All Platforms

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#313]
### Summary
As mentioned in [#1025](https://github.com/luna/luna-studio/issues/1025), the current rename functionality does not work across all systems. This issue will fix the underlying functionality in Luna for integration into Luna Studio. 

### Value

- The package rename functionality works correctly on all systems.

### Specification

- Fix the underlying cause of the bug described in [#1025](https://github.com/luna/luna-studio/issues/1025).

### Acceptance Criteria & Test Cases
- [x] Package renaming works properly in Luna.

**Comment by piotrMocz** [comment]
This PR didn't fix https://github.com/luna/luna-studio/issues/1025 -- if it needs some more integration with Luna Studio, then the description misled me ;)

**Comment by iamrecursion** [comment]
That’s my mistake. Yes the description is unclear. This fixes the underlying bug in Luna, but the fix still needs integration with Luna Studio. 

Sorry for the confusion.

**Comment by iamrecursion** [comment]
This is now fixed.
