### ISSUE TITLE
GHC as a JIT Component

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#321]
### Summary
It would be brilliant to leverage the years of accrued optimisations for GHC Core in GHC, were it used as a target for Luna. However, to do this some understanding needs to be gained about how GHC may interact as part of a JIT compiler pipeline. 

This is effectively suggesting writing an RTS in Haskell, and using GHC as it's JIT. 

### Value
Some idea will be gained as to whether GHC would be a viable component as part of a JIT compiler architecture. 

### Specification

- Investigate fine-grained control of GHC's optimisation pipelines.
- Investigate execution performance of GHC as part of a JIT pipeline.
- Recommend whether this is a viable approach for the Luna runtime. 

### Acceptance Criteria & Test Cases

- [x] The research is incorporated into the [Runtime RFC](https://github.com/luna/luna-rfcs/blob/runtime-design/text/0000-runtime-design.md). 
- [x] The research is sufficient for comparison with GraalVM and LLVM as alternative solutions.

**Comment by iamrecursion** [comment]
#### GHC Core as a Compilation Target

**Comment by iamrecursion** [comment]
#### GHC's Optimiser Pipeline

**Comment by iamrecursion** [comment]
#### Dynamic Loading of GHC-Generated Code

**Comment by iamrecursion** [comment]
#### GHC via LLVM Code-Generation

**Comment by iamrecursion** [comment]
#### GHC Performance in a JIT'ed Workflow.

**Comment by iamrecursion** [comment]
#### Bundling GHC and the GHC API.

**Comment by iamrecursion** [comment]
#### Pipeline Complexity

- While GHC's optimiser incorporates years of experience in the optimisation of functional programs, GHC itself would only be _one_ portion of the JIT pipeline. 
- GHC itself does not have any JIT inbuilt (unlike LLVM - see #325), and so a JIT harness would need to be built around GHC itself.

**Comment by iamrecursion** [comment]
#### Using GHC as a JIT Component via the GHC API

**Comment by wdanilo** [comment]
"GHC's compilation performance is not amazing, especially for complex code." - I suspect the performance is regarding type checking. We need to check exactly what is the performance after core generation and I suspect its pretty nice.

**Comment by iamrecursion** [comment]
> 
> 
> "GHC's compilation performance is not amazing, especially for complex code." - I suspect the performance is regarding type checking. We need to check exactly what is the performance after core generation and I suspect its pretty nice.

Correct, but this is the entire point of this research! It's not really at a discussion stage yet, hence why all the topics are so sparse.

**Comment by iamrecursion** [comment]
#### Miscellaneous Thoughts

- Utilising GHC as a backend for the runtime is an implicit statement that we will never be faster than GHC is at the current time.

**Comment by iamrecursion** [comment]
#### Interaction with GHC-JIT and Luna's FFI

- FFI calls when actually _compiling_ code should be translated to core that links in the FFI call as Haskell does. 
- This gives a huge performance boost over the current libffi + system dynamic linker solution.

**Comment by iamrecursion** [comment]
This analysis has been incorporated into the WIP RFC as of [`6765451`](https://github.com/luna/luna-rfcs/commit/6765451921f2bacec6881952697cbe61fdb03b1b).
