### ISSUE TITLE
Missing config.yaml file in a project casues exception on rename

### ISSUE THREAD

**Issue by mikusp** [luna/luna#336]
Please ensure that you are running the latest version of Luna before reporting the bug! It may have been fixed since.

### General Summary
Saving a project without config.yaml file errors with `/path/to/config.yaml is inaccessible`.

### Steps to Reproduce

Please list the reproduction steps for your bug. For example:

1. Open of our tutorials, e.g. TramsPlayground
2. Hit Ctrl-s, provide name and press Enter

### Expected Result
Project is saved at new location
### Actual Result
Exception written as above
### Luna Version

- Please include the output of `luna --version`.

**Comment by iamrecursion** [comment]
Fix is in Luna master as of [443fe25](https://github.com/luna/luna/commit/443fe25722269e62ddaf6d6ce48ca736b0fdfe18).

**Comment by iamrecursion** [comment]
Merged to Luna Studio master as of [461c0d1](https://github.com/luna/luna-studio/commit/461c0d1a58dcd90174046fb4dc43c875ca9771ef).
