### ISSUE TITLE
Please Tag Releases!

### ISSUE THREAD

**Issue by Vaelatern** [luna/luna#344]
Please ensure that you check the latest version of Luna to see if your feature has been implemented.

But that's the problem. From the sources, how can I know I'm building the latest version?

### General Summary

Tags in the repo, so I can get a particular tag and know I'm getting the correct version.

### Motivation

- It's hard, as a package maintainer, to ensure our users have the latest packages, unless we have version numbers to compare. Commits for versioning are basically useless, because they change with every commit, and not every commit is a version unto itself.
- Void Linux, for example, has a policy of not accepting any software for its package repositories that doesn't come with a tagged release.

**Comment by iamrecursion** [comment]
The current status of the Luna Compiler is that it doesn’t have any official releases. We do tag releases of [Luna Studio](https://github.com/luna/luna-studio), as you can see under [releases](
https://github.com/luna/luna-studio/releases). Once we start to make official releases of the Luna toolchain we’ll definitely tag those releases, but right now we don’t really have milestones to tag. 

Does working from Luna Studio’s releases do what you want, or do you explicitly want releases of the Luna toolchain itself?

**Comment by iamrecursion** [comment]
There is very little that the command-line currently offers that Luna Studio doesn’t. The one separate feature currently is that you can execute standalone scripts in a one-off mode from the command-line. If you think it’s useful I’m sure we could start making official releases of the command-line, even if we don’t build them ourselves.

**Comment by Vaelatern** [comment]
I'm sure for actually deploying Luna tools in any place other than under a user's direct control such capabilities would be essential.
Is Luna meant to write programs beyond simple prototypes, or beyond with what a user directly interacts (background, server daemons)?

**Comment by iamrecursion** [comment]
Oh, definitely, but the language is still under heavy development so doing so would be inadvisable until we stabilise. We definitely intend to start official releases when we do so, but if you want them before that point I'll get them started!

**Comment by iamrecursion** [comment]
Just to update on this, we’re making real progress on making packaged releases of the Luna command-line tools.
