### ISSUE TITLE
Fix the CI build

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna#346]
### Summary
Currently all CircleCI builds of Luna fail. They should succeed.

### Value
Having working build is useful, because it helps us see when code starts to fail to build or pass the tests.

### Specification
Fix whatever is immediately fixable.
Disable failing parts and file separate issues for them otherwise.

### Acceptance Criteria & Test Cases
There should be a green checkmark next to the commit in github web UI after CircleCI finishes processing it.

**Comment by iamrecursion** [comment]
This is done.
