### ISSUE TITLE
FFI calls performance problem

### ISSUE THREAD

**Issue by radeusgd** [luna/luna#347]
### General Summary
FFI calls are currently taking a long time (0.1-0.2 ms per call which amounts to 10k calls per second).

### Motivation

When using Luna to run multiple iterations of some FFI operation the call overhead is very noticeable and execution is an order of magnitude slower than in other languages.

Example benchmark (with code) can be found here: https://github.com/Luna-Tensorflow/Luna-Tensorflow/blob/037a73755d91423eb7c5aa9c7285243e820871db/API/Tensorflow/src/Main.luna

**Comment by mikusp** [comment]
I think you are measuring performance of lookupSymbol function, not calling the resulting pointer. Please try to call lookupSymbol once beforehand and using returned function pointer in subsequent iterations.

**Comment by mwu-tow** [comment]
Well… I'd say that's the current luna performance.
If you want to have many thousands of iterations, you should do it in C++. Or stay in Luna, but it will be slow until the performance work is done. 
See https://github.com/luna/luna/issues/239 for another case of slowness.
See https://github.com/luna/luna/issues/251 as a primary issue for tracking performance related stuff.

@mikusp  Even if it was measuring performance of `lookupSymbol`, the numbers shouldn't be that bad. I have heavily optimised that routine, see https://github.com/luna/luna-core/pull/133 These functions take about ~50 ns overhead on repetitive calls.

**Comment by iamrecursion** [comment]
This will be fixed as part of the work on the new Luna runtime.
