### ISSUE TITLE
Luna Standard library FieldModifications test does not parse

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna#355]
### General Summary
There is a test in standard library tests that fail during the parsing.
See the `StdTest.Lang.FieldModifications` test.

### Steps to Reproduce
Try running the standard library tets with FieldModifications test enabled (see https://github.com/luna/luna/pull/354/files#diff-b5d9ec7eef4f228015af311b2bee25e8 )

### Expected Result
Tests should succeed.

### Actual Result
A parser error is reported like below: 
```
TODO: AstModifier Modifier ("+")
CallStack (from HasCallStack):
  error, called at src/Luna/Pass/Parsing/Parser.hs:413:10 in luna-syntax-text-builder-0.2-7l2FQ8FMYuJKw0SjQMhl1H:Luna.Pass.Parsing.Parser
```

### Luna Version

- Please include the output of `luna --version`.

**Comment by iamrecursion** [comment]
Closing as this is subsumed by #312.
