### ISSUE TITLE
Overly Long StdTest Execution Time on CI

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#361]
### General Summary
When executing `StdTest` locally (`stack exec luna -- run --target "./stdlib/StdTest/"), it takes approximately 1 minute to execute in a non-release build (i.e. one with `fomit-interface-pragmas` enabled). The amount of variation observed is 

When doing the same on CI, StdTest executes

### Steps to Reproduce

1. Build luna locally.
2. Execute `time stack exec luna -- run --target "./stdlib/StdTest/" (or some windows equivalent if `time` is not available).
3. Rebuild on CircleCI
4. The time spent for the execution of `StdTest` will be ridiculously long in comparison. 

### Luna Version
```
luna (linux-x86_64) (ghc-8.4) [wip/in-tree@59cf9197c8bf25a99b932af066e695236c0deecc, Dirty, 1454 commits, latest on Mon Feb 25 16:45:47 2019 +0000] 
```

**Comment by iamrecursion** [comment]
It should be noted that this appears to be specific to CircleCI, as we have not been able to reproduce it locally successfully yet. It does not occur on Azure Pipelines CI.

**Comment by iamrecursion** [comment]
@mwu-tow: Do you think it possible to run the CI process in the CI docker image locally to check if it’s configuration-based or an artefact of CircleCI’s shared machines?

**Comment by mwu-tow** [comment]
@iamrecursion  I haven't tried but it seems to be supported: https://circleci.com/docs/2.0/local-cli/#run-a-job-in-a-container-on-your-machine

**Comment by iamrecursion** [comment]
No longer relevant. Will investigate if it ever appears in the wild again.
