### ISSUE TITLE
IDE Protocol

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#365]
### Summary
As part of the implementation of the new runtime, the Luna CLI binary should support operating with some kind of IDE protocol. For Luna Studio's use this will likely be more rich than [LSP](https://github.com/Microsoft/language-server-protocol), but it should also support operation in LSP mode to allow for ease of interoperation with other editors.

### Value
Currently, the implementation of Luna Studio uses code from the Luna compiler directly. This increases the implementation burden as LS is inherently tied to any internal changes in the compiler. This is an undesirable state of affairs to say the least. 

In an ideal world, Luna Studio will be written purely in (some variant of) JavaScript, and will not have to have any Haskell components. This will be achieved by delegating all of the heavy lifting for the Luna language to the Luna compiler binary and its language server prototcol, thereby removing any true coupling between the two. 

### Specification
The IDE protocol implementation must support the following features:

- A textual format (non-binary) for communication with IDE protocol clients (JSON?).
- Performance such that its use is seamless when compared to services running as part of the editor process.

It may be possible to implement the additional features required by LS as extensions to LSP, hence reducing the total implementation effort required to provide this functionality. Furthermore, the IDE Protocol implementation should be suppported by comprehensive tests and benchmarks such that it is easy to detect and fix regressions should they happen.

One of the main sticking points in supporting LSP and a richer IDE protocol is that we want to be able to do things that require attaching semantic metadata to the file in question. LSP has little to no support for rich compiler output, with deep assumptions that code is plain-text, or at most markdown. This means that it becomes much harder to easily support things such as semantic highlighting, doc summaries with interactive examples, and interactive error messages (amongst other highly-interactive features). 

A particularly interesting point is the lack of support for semantic highlighting, something that the existing hacky implementation for Luna already does. We definitely need to support it going forward, which likely means being divorced from LSP or at least creating many extensions on top of it. 

The upshot of this is that even if we do support LSP, we’ll likely have to have ‘LSP Mode’ and ‘full mode’. This begs the question of whether LSP support is even worth it. If we need all these extensions to provide our ideal interactive editing experience for Luna, then arguably every client of the IDE protocol should do also.

It must support the following requests/commands:
- Completion Requests: Get completion items from the language server at a given cursor position.
- Hover Information: Sends current textual position to get information (e.g. documentation) about the item under the cursor position.
- Inspect Type: Gets the type of the item under the cursor.
- Insert Type: Inserts the type for the item under the cursor in a relevant place. 
- Go to Declaration: Returns the location of the declaration of the symbol at the provided position.
- Go to Definition: Returns the location of the definition of the symbol at the provided position.
- Find References: Find references in the current project to the item at the provided position.
- Highlight: The Language Server should provide highlighting information for each atom of text, allowing the editor to greatly simplify highlighting. 
- List Symbols: Should list all symbols in a given file.
- Code Action: Apply changes (e.g. hotfixes) to code.
- Format Code: Apply a formatting style to the provided range (can be a selection or the whole document). This may also work for live formatting while the user is typing.
- Rename Symbol: Tell the language server to perform a project-wide symbol rename.
- Get Folds: Find ranges that can be folded within a document.
- Get Hints: Hints for the document or provided location, which can then be applied as quick fixes. This should account for any alterations to syntax.
- Get Fits for Holes: Luna wants to support holes that can be matched by type. 
- Get Documentation: Get and display the documentation for the object at the given position. 
- REPL: The IDE protocol needs to have flexible support for interacting in a programmatic fashion with the Luna REPL, allowing for interactive development. This should include ‘evaluate under cursor’, but also functionality to trivially go back from REPL to buffer if need be. 
- Debugging: The user should be able to place break-points, and easily inspect values during execution of a program. This requires REPL support and IDE protocol support. This debugging functionality should allow for hot-reloading of code, changing of values within a live program (though this is already mostly supported by Luna Studio’s graph), and various other debugger functionality (step over, step in, step out, continue, etc). In future, this could also be extended to support hardware watchpoints and other low-level details as necessary. 

From an architectural standpoint, all this functionality needs to be implemented as a separate library, as a REPL would be, as part of the Luna project. While it should be decoupled as much as possible from the implementation details of the compiler/core/type checker/etc, it inherently will need to utilise those APIs.

### Acceptance Criteria & Test Cases

- The above listed features have been implemented.
- Performance of the IDE protocol is indistinguishable from in-process language servers.
- The IDE Protocol implementation comes with comprehensive tests and benchmarks.

**Comment by iamrecursion** [comment]
There has been some discussion (via email) regarding the design of a unified IDE protocol for dependently-typed functional languages that both Idris and Luna (as a start) could support. Thoughts will be included here as those discussions develop.

**Comment by kustosz** [comment]
This should also include visual syntax support

**Comment by iamrecursion** [comment]
A brief note about how support for the visual syntax could be handled.

- The compiler knows type information about all functions.
- It can also track node and visualisation state internally.
- The protocol message can, in addition to the positions of the nodes, can send the types of controls for expanded nodes.
