### ISSUE TITLE
Parser breaking at /=

### ISSUE THREAD

**Issue by radeusgd** [luna/luna#368]
### General Summary

Upon parsing following code:
```
def main:
	if 0 /= 1 then 0 else 1
```
instead of just working or getting a normal parse error, the interpreter crashes.
### Steps to Reproduce
1. Create a file with content as above
2. Enter the file's directory.
3. Execute `luna run --target thatfile.luna`.

### Expected Result

Syntax error or program accepting the /= operator.

### Actual Result

Interpreter error
```
Using standard library at "/home/radeusgd/Projekty/luna/stdlib/"
TODO: AstModifier Modifier ("/")
CallStack (from HasCallStack):
  error, called at src/Luna/Pass/Parsing/Parser.hs:408:10 in luna-syntax-text-builder-0.2-7yA4WhnsJHH81KYQ4YnNCT:Luna.Pass.Parsing.Parser
```

### Luna Version

luna (linux-x86_64) (ghc-8.4) [linter@17a7b6b7eccdb6c1137920013ba23ff3c231bc44, Dirty, 1465 commits, latest on Mon Mar 4 19:23:53 2019 +0100]

(the only changes are in Luna shell, the interpreter code is identical to current master: 88803b0a8afd3f72265c0c9fe44c0f7aaf02eb73)

**Comment by iamrecursion** [comment]
Subsumed by #312. Closing.

**Comment by iamrecursion** [comment]
In essence, `/=` is being parsed as field modifier, not a negated EQ. Needs to be fixed.

**Comment by wdanilo** [comment]
@iamrecursion I'm not sure. Basically, there is a general rule that if you put `=` after an operator, you get a field modifier. You've got a division operator `/`, so it's field modifier is `/=`. Using `/=` as "not equals" would be an exception from that rule and we rather don't like exceptions. I'd consider going the other way and using `!=` instead and assuming that there is no `!` operator.

**Comment by iamrecursion** [comment]
Well we _need_ a `!` operator for negation, so either way you’re special casing something.

**Comment by mwu-tow** [comment]
There's also the `==` operator itself.

**Comment by wdanilo** [comment]
@mwu-tow `==` is not a valid case here as the `=` is already a special kind of an operator and having a modifier `==` would not make sense. 

@iamrecursion I would rather not special case something. There are many other options possible / questions involved:
- Should we allow for prefix operators? I know that `not` operator would be cool, but we've got an incredibly small amount of use cases for them so far, so maybe its better to go the Haskell way here (this is still an open discussion and we need to finish it soon)
- Should `!` be the negate operator? Why not `~`? From a mathematical perspective, it's much more valid to use `~` for that purpose. Moreover, we were planning to use `!` as a syntax for possible errors like, `foo : Int in IO ! IOErrror`. Then it would be compatible with `!=`, as there would not be an `!` operator.

**Comment by wdanilo** [comment]
Please continue here: https://github.com/luna/luna/issues/312
