### ISSUE TITLE
Crash When Using Qualified Type Name in Expression

### ISSUE THREAD

**Issue by radeusgd** [luna/luna#382]
### General Summary
Attempting to execute a file with a fully-qualfied name in an invalid position causes the compiler to crash with an error. 

### Steps to Reproduce

Create a project with files:
DblColumn.luna:
```
import Dataframes.Types
import Dataframes.Column

def columnFromList name list:
    col= Column.fromList name Dataframes.Types.DoubleType list
    col
```
and Main.luna
```
import ImportExample.DblColumn

def main:
    col = columnFromList "rand" [1.0, 2.0, 3.0]
    None
```
### Expected Result
An intelligible error message instead of a call to `error` and the resultant crash. 

### Actual Result
```
MethodImporter.solve: unknown name Dataframes.Types.DoubleType.DoubleType on a3 . Types . Dataframes.Types.DoubleType.DoubleType
CallStack (from HasCallStack):
  error, called at src/Luna/Pass/Typing/MethodImporter.hs:81:13 in luna-passes-0.1-FSBbUS7HbwEAaUmlwoSkhJ:Luna.Pass.Typing.MethodImporter
```
or in the attached example
```
Using standard library at "/home/radeusgd/Projekty/luna/stdlib/"
MethodImporter.solve: unknown name Dataframes.Types.DoubleType.DoubleType on a3 . Types . Dataframes.Types.DoubleType.DoubleType
CallStack (from HasCallStack):
  error, called at src/Luna/Pass/Typing/MethodImporter.hs:81:13 in luna-passes-0.1-FSBbUS7HbwEAaUmlwoSkhJ:Luna.Pass.Typing.MethodImporter
```

### Luna Version
```
luna (linux-x86_64) (ghc-8.4) [master@3424c79a983995ac1040c767ef6495ffa69ffeb3, Clean, 1469 commits, latest on Thu Mar 21 15:44:08 2019 +0100]
```

**Comment by radeusgd** [comment]
Project in which you can just cd into and run `luna run` to see the issue:
[ImportExample.zip](https://github.com/luna/luna/files/3013054/ImportExample.zip)

**Comment by iamrecursion** [comment]
Can you clarify what you expect to happen here? `Dataframes.Types` isn't available to the interpreter and that's what it's telling you.

**Comment by kustosz** [comment]
@iamrecursion in fact what happens here is the use of qualified type name in expression is invalid. And for whatever reason that results in a hairy exception instead of a nice, well localized in the expression, error. What should happen is that it should show a standard compile error, not an exception.

**Comment by iamrecursion** [comment]
Ah! I misinterpreted the error call. Shows how useful proper type errors are. :'D
