### ISSUE TITLE
Interpreter setting `LUNA_LIBNAME_DATA` env variable 

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#389]
### General Summary

Interpreter should set `LUNA_LIBNAME_DATA` environemnt variable to an absolute path to data/ directory in the given library

### Motivation

Given that:
a) sample resources are library-specific and generally should be updated along with the library
b) snippets are even closer tied to library
I'd say both should be part of Luna library package layout. Just like we have src and native_libs subfolders, interpreter should also support data directory. So, in final package, it'd end up under env/stdlib/Dataframes and env/stdlib/Std respectively.

Then following idea:
Interpreter iterates over libraries anyway (indexing for searcher, looking for their native_libs) — so when iterating, it should also check for data/ subdirectory. If it is present, it should set LUNA_LIBNAME_DATA environemnt variable to an absolute path to data/ directory in the given library. (where LIBNAME is a library name as deduced from path, e.g. STD or DATAFRAMES)

User code (and snippets as well) should use the environment variable to access the data (eg. pseudocode Table.read $ getenv "LUNA_LIBNAME_DATA" </>  "sampleTable.csv").
That basically:
* keeps snippets portable (works on any installation with the same code)
* keeps updates localized
* extensible (new libraries / packages can come with their own sample data)
* various libraries don't collide when providing files with the same name

**Comment by iamrecursion** [comment]
Is this done @sylwiabr?
