### ISSUE TITLE
Filepaths handling

### ISSUE THREAD

**Issue by kustosz** [luna/luna#399]
### Summary
There was recently some discussion around handling paths in Luna (what should the separator be, how should we treat env vars etc.).
This task entails design and implementation of the final solution of this problem.

### Value
Unified, sensical and safe filepaths system!

### Specification
TBD

### Acceptance Criteria & Test Cases
Consensus for the solution, TBD.

**Comment by kustosz** [comment]
See https://github.com/luna/luna/pull/394#discussion_r274083717

**Comment by iamrecursion** [comment]
For a list of things that need discussion so far:

- Environment variable expansion in paths.
- The `FilePath` type and its conversions.
- `FilePath` literals, and handling of path separators (should we allow use of both on all systems, should we use a single internal representation, should we store paths in a semi-canonicalised form, etc).
