### ISSUE TITLE
Documentation Parser

### ISSUE THREAD

**Issue by sylwiabr** [luna/luna#406]
### Summary
Luna syntax parser reads source files and outputs an AST (Abstract Syntax Tree). Currently, all the comments are read as a single token (a text). We need to create a separate parser which will consume the comment text and will return a Comment-AST. 

### Value
We will be then able to traverse comments structure and nicely display them in the documentation and interactive help. 

### Specification
Write a parser using the [Attoparsec](http://hackage.haskell.org/package/attoparsec) library. Attoparsec is the right choice here because documentation parser should never fail and it should work fast. 

### Reference Implementations
- Syntax Lexer: https://github.com/luna/luna/blob/master/syntax/text/lexer/src/Luna/Syntax/Text/Lexer/Grammar.hs
- Syntax parser: https://github.com/luna/luna/blob/master/syntax/text/parser/src/Luna/Syntax/Text/Parser/Parser/Class.hs
Current Luna parsers is implemented here (for reference) 

### Acceptance Criteria & Test Cases
Parser code should be benchmarked and tested and we expect the resulting parser to be able to parse megabytes of text per second. For further details regarding the desired syntax, please ping @wdanilo.

**Comment by jcmincke** [comment]
@wdanilo : Do you have any specs/grammar for that syntax?
