### ISSUE TITLE
I cannot run luna

### ISSUE THREAD

**Issue by sobelek** [luna/luna#422]
### General Summary
After installing any version of luna I get the same message
`bin/public/luna-studio/luna-studio: symbol lookup error: /tmp/.mount_luna-sWCHi24/usr/lib/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
`

I am using manjaro with Plasma
Kernel 5.4.23
### Steps to Reproduce

run `luna-manager install `
run `luna-studio`
### Expected Result
Expected luna to start

### Actual Result
I get
`bin/public/luna-studio/luna-studio: symbol lookup error: /tmp/.mount_luna-sWCHi24/usr/lib/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
`

### Luna Version
Tested on 1.9 1.8 1.7 1.6

**Comment by erindru** [comment]
I am also having this problem, on Fedora 31

**Comment by wdanilo** [comment]
Interesting. The bad info is that it will not be fixed in 1.x. The good info is that 2.0 will not depend on that and will not have this problem (to be released mid year). Thank you for reporting, we highly appreciate it!

**Comment by shalva97** [comment]
just discovered this project 5 hours ago and all i do is to get this installed. 
GUI installler didnot even open, complaining about pango something
![image](https://user-images.githubusercontent.com/22417494/96310425-5c603300-1018-11eb-8488-ebee629ec183.png)
then downlaoded Windows installer and tried to use Wine but did not work... using steam proton also nothing...

then randomly i noticed there where cli installers, come on, there are worst instructions on installation. there is just a website linked to "download Luna Studio"

> We strongly encourage you to download Luna Studio and play with interactive tutorials

there are no instructions on how to use CLI on the doc, also completly randomly i run `luna-manager install` and it sort of worked and... well there where no installation finished message.

and now of course i have same error as above. why did you closed this issue without a workaround? why there are no instructions about installing or troubleshooting? this is bad...

OS: Arch Linux

**Comment by shalva97** [comment]
@wdanilo hello?

**Comment by joenash** [comment]
Hey @shalva97,
We are currently not addressing bugs with the version you are trying to install (Luna 1.9 and below), whilst we work on 2.0 ("Enso"). The reason for this is that Enso is a complete rewrite, on a fresh codebase, and to deliver that version we have [archived](https://github.com/enso-org/luna-archive) Luna. 

Enso is not quite ready for prime time usage yet, but is getting close. You can follow it's development on our [devblog](https://medium.com/@enso_org), and if you want to try it, [you can find the instructions here](https://dev.enso.org/docs/enso/getting-enso.html#getting-enso).
