### ISSUE TITLE
Parser errors should contain line number

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna#57]
At the very least: Ideally they would tell you (natural language) what's wrong with the code.

Right now the numbers are very misleading: I expected them to be line/column numbers but I quickly found out they are not that :D

**Comment by sporgj** [comment]
Can I tackle this task as a beginner?

**Comment by wdanilo** [comment]
@sporgj  Yes, of course! It should not be very hard to do, however there will be some tricky parts I think. Contact me in case of any problems, I'll guide you!

**Comment by wdanilo** [comment]
Done in new parser
