### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [luna/luna#59]
I would like to point out that identifiers like "[```__LUNA_AST__```](https://github.com/luna/luna/blob/6d3f22cd6a8eb96243be016974a453131367ca49/src/ast.h#L8)" and "[```__LUNA_TOKEN__```](https://github.com/luna/luna/blob/bbff5cb204b127f9a5e9845bc96d7be87d37044c/src/token.h#L8)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by glhrmfrts** [comment]
I vote for something like `LUNA_AST_H`

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/luna/luna/commit/9b6639653e759868017a7155d3ac1372396515eb "Deletion of a few underscores").
