### ISSUE TITLE
stack install fails on not finding visualization-api.git

### ISSUE THREAD

**Issue by gdmcbain** [luna/luna#65]
Following the instructions for installation in [README.md](https://github.com/luna/luna/blob/master/README.md), the `stack install` failed with 

> fatal: repository 'https://github.com/luna/visualization-api.git/' not found

I think this comes from [`shell/stack.yaml`, line 55](https://github.com/luna/luna/blob/master/shell/stack.yaml#L55).

```
location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'https://github.com/luna/visualization-api.git'}
```

**Comment by piotrMocz** [comment]
@gdmcbain could you please try again? We double-checked the permissions and now everything should work fine.

**Comment by gdmcbain** [comment]
Thank you, but this time (with a fresh git clone), I get

> fatal: Authentication failed for 'https://github.com/luna/monad-branch/'

**Comment by piotrMocz** [comment]
Thanks for reporting that: seems like we missed some of our repositories when opening the access. Terribly sorry for your inconvenience, it should be accessible now.

**Comment by gdmcbain** [comment]
Thank you.  Seems to be working now; the `stack install` has moved on to downloading, configuring, & building standard third-party packages from Stackage (HUnit, OneTuple, …).
