### ISSUE TITLE
What happened to the project?

### ISSUE THREAD

**Issue by glhrmfrts** [luna/luna#68]
What happened to Luna? I found it some time ago, and waited for a while to see if it had any activity but i didn't see any, so is the project dead? Or it moved to somewhere else?

I would love to contribute if I knew someone would still want to work on this with me.
I don't even know if someone will reply to this, but it doesn't hurt to try...

**Comment by tj** [comment]
yep, pretty much dead, haven't had any time

**Comment by glhrmfrts** [comment]
So you wouldn't accept any PRs then?

**Comment by tj** [comment]
doubt I'd have time but I can add you to the repo if you're interested!

**Comment by vendethiel** [comment]
Tj moved on to go-er lands :P

**Comment by glhrmfrts** [comment]
@tj I'd be greatful if you do that!

**Comment by tj** [comment]
done!
