### ISSUE TITLE
Parametric Types Don't Mention Referenced Properties

### ISSUE THREAD

**Issue by puffnfresh** [luna/luna#73]
Given a function which uses properties on a value:

![1516183545](https://user-images.githubusercontent.com/37715/35037020-3d5b3a82-fbca-11e7-9640-706bcdb94919.png)

The type doesn't mention the referenced properties:

![1516183527](https://user-images.githubusercontent.com/37715/35037021-3d98c2b2-fbca-11e7-8423-7c3a7c569ed9.png)

I read the polymorphism as "forall b d" but it seems like I can't use the function for all types, I can only use the function when the value has a "mappend2" method.

Is the type I'm reading in the use of "mappend" accurate? Is it just not being printed correctly?

I see this as a big problem, because I can't determine the implementation of a function by reading the type, like I can usually do with polymorphic types. I don't know what values a function can take by looking at the type.

**Comment by wdanilo** [comment]
You understand the types correctly, they are printed in too simplified form.

> I see this as a big problem, because I can't determine the implementation of a function by reading the type, like I can usually do with polymorphic types. I don't know what values a function can take by looking at the type.

Valid point.
We do not display it now just to keep the graph view clean. We should allow you to see more detailed type inferred by TC. We have to talk about it @kustosz

**Comment by kustosz** [comment]
For this, rather simple, case we can have a quick fix. The output port can be typed as:
```
b -> d -> b.mappend2 d
```
What happens now is that when we see an unsolved application typing rule, we fallback to `*` in GUI.
Of course, this is not enough for more complex code samples (i.e. when the assumptions aren't directly referenced in the return type) – for that we'd need some kind of a "type debugger" view, where you can see all the assumptions on your types.
The top of my head instance of when the solution above does not work is:
```
def foo a:
    a.bar 1
    None
```
In this case the `a` is not referenced by the return type and the whole thing types as:
```
a -> None, such that a.bar accepts an Int
```
Now to design a clear way of presenting the `such that` part in the GUI and we're good to go :)
