### ISSUE TITLE
Installation error on Windows: Prelude.head: empty list

### ISSUE THREAD

**Issue by acailly** [luna/luna#76]
On a Windows 7 64 bits, I just: 
- downloaded and installed the Haskell tool stack: https://www.stackage.org/stack/windows-x86_64-installer
- downloaded the luna installer for windows: http://packages.luna-lang.org/windows/lunaInstaller.zip
- launched the installer
- entered my email and clicked next
- clicked install
- this error appears: Prelude.head: empty list

And no way to test luna :cry:

**Comment by acailly** [comment]
Seems related to https://github.com/luna/luna/issues/77

**Comment by wdanilo** [comment]
@acailly Thank you so much for so detailed steps explanation! it is great. You are right, these issues are related.

**Comment by kustosz** [comment]
This is fixed now. If you redownload the installer from http://packages.luna-lang.org/windows/lunaInstaller.zip, the issue should disappear.
