### ISSUE TITLE
luna command line - compilation of example file fails ("Pattern match failure")

### ISSUE THREAD

**Issue by holtzermann17** [luna/luna#78]
I've tried to compile the example at the bottom of https://github.com/luna/luna on the command line, following directions there. Here's what I see as output:

```
joe@ubuntu:~/luna-test$ luna
Found the standard library at: /home/joe/luna/stdlib/Std
Requested module: Std.Base
Compiling module: Std.Base
Requested module: Std.HTTP
Compiling module: Std.HTTP
Requested module: Std.System
Compiling module: Std.System
Requested module: Std.Time
Compiling module: Std.Time
Requested module: Std.WebSockets
Compiling module: Std.WebSockets
Requested module: luna-test.Main
luna: user error (Pattern match failure in do expression at src/Luna/Shell.hs:139:5-18)
```

**Comment by holtzermann17** [comment]
Oh, my bad. It's case sensitive.

```~/luna-test/src$ mv main.luna Main.luna```

then rerun, that fixed it.

**Comment by wdanilo** [comment]
Wait! It is still a bug. "Pattern match failure" should never happen, there should be better error there. Reopenning. Thanks for reporting!

**Comment by kustosz** [comment]
@holtzermann17 also heads up: the name of the project itself should also be CamelCase. It won't become a problem until you have many files, but in Luna, the name of the project is the first part of the module name. E.g. Our standard library is a project named `Std` and it has modules like `Base` or `System` inside and these are imported as `Std.Base` or `Std.System`. If your project is named `luna-test` you won't be able to import the modules – `import luna-test.Foo` won't parse.

**Comment by piotrMocz** [comment]
This is fixed. Right now when I don't have a `Main.luna` file in my project sources and I run `luna run` I get the following error:
```
UnitSourcesNotFound [] (Qualified "Testproj.Main")
```
It is a matter of discussion whether this error is human-readable, but it's not a pattern match failure.
