### ISSUE TITLE
Use a developer certificate for macOS version

### ISSUE THREAD

**Issue by florianginetta** [luna/luna#80]
When trying to install the prebuilt binary for macOS, the system throws a warning about unsigned code. To improve credibility, you might want to consider to build using an Apple Developer Certificate.

Looking forward to using Luna!

<img width="547" alt="bildschirmfoto 2018-01-17 um 17 21 29" src="https://user-images.githubusercontent.com/30113109/35053600-e1278398-fbaa-11e7-9b4b-462bb3f6f300.png">

**Comment by wdanilo** [comment]
Thank you for reporting this issue. We are in the process of getting the certificate but it takes ages for Apple to grant it. It will be soon. For now, just right mouse click on the icon and select run from the context menu.
