### ISSUE TITLE
c9.io Performance Issues

### ISSUE THREAD

**Issue by salmazov** [luna/luna#85]
![image](https://user-images.githubusercontent.com/1635615/35084881-25d2ab26-fc37-11e7-8f25-6b6201cbaadf.png)

I tried Luna with luna basic official example in terminal mode compiling. Whooops! About 20 minutes? Seriously?

c9.io params:
HDD: 4782 mb
RAM: 2.5 Gb 
Processor: I don't know what c9.io provide, but it was about 250% of CPU load.

So what a you thinking, dear Luna developers, about this? ;)

**Comment by wdanilo** [comment]
I don't know what to think about it yet, because it works instantly here. We've got to investigate it. Thank you for reporting it!

**Comment by salmazov** [comment]
Thank you a lot for response! ;)

So it will be great if Luna provides convenient and speedy experience for terminal/console users.

**Comment by wdanilo** [comment]
Of course it should! I'm sorry that you have this issue. We're still in beta and sometimes really strange things happen on different configurations. Hello world compiles here literally instantly. We are currently under heavy load of urgent tasks, but will look at it soon!

**Comment by kustosz** [comment]
Just a question for reference – did you compile the executable with `--ghc-options="-O2"`? That improves the times significantly and should bring the execution time to under a minute. Yes, that's still terrible, but much better.

**Comment by salmazov** [comment]
![image](https://user-images.githubusercontent.com/1635615/35508764-a30b60fa-0502-11e8-886d-c4a53c4d0d49.png)
It's better, yes :)

**Comment by kustosz** [comment]
Well, better, yes... though I wouldn't say it's any good. Anyway I'll be closing this issue now – there's nothing we can do for now, other than speed up our performance efforts. It will all be much faster in the coming months. Sorry it's so painfully slow now :(

**Comment by salmazov** [comment]
Thank you! Stay in touch.
