### ISSUE TITLE
Windows executable on the site is not signed

### ISSUE THREAD

**Issue by varosi** [luna/luna#87]
This leads to multiple Windows messages for unsafe code on Windows 10.

**Comment by wdanilo** [comment]
@kustosz Is this related to what you've been explaining to me? Are we able to fix it or we have to wait until Windows start trusting us?

**Comment by varosi** [comment]
Nope, you have to fix it. It needs signing of executables with a certificate for executables signing. It's usually part of deployment process.

**Comment by wdanilo** [comment]
@varosi I was speaking with our team today about it. We will handle it soon. If there will be any questions, we will also ask you fro further help with that!

**Comment by piotrMocz** [comment]
This is a duplicate of https://github.com/luna/luna-studio/issues/1049 so I suggest the conversation is moved there (that issue has nice pictures, so it's better ;)).
