### ISSUE TITLE
Extend Pretty Printer to Differentiate Between Self and Other Arguments

### ISSUE THREAD

**Issue by kustosz** [luna/luna#9]
With this code
```
a = 10
b = a . succ
c = a + a
```
we'd like to shorten (dotify) the `a` in `c`, and keep the one in `b` untouched. Current approach requires us to treat both occurences the same way, no matter their positions in the respective expressions.

**Comment by wdanilo** [comment]
It's pretty printer, not a breaking change here. Btw I feel it would soon be obsolete as we are simplifying the text above nodes.
