### ISSUE TITLE
BasicsTutorial does not create a circle node

### ISSUE THREAD

**Issue by MCluck90** [luna/luna#91]
## Specifications

OS: Windows 10
Versions: 1.0 and 1.0.1

## Steps to Reproduce

1.   Launch Luna Studio
2.   Open the BasicsTutorial project
3.   Click "Next" on the "Welcome to Luna!" message box
4.   Click inside of the Node editor window
5.   Press H
6.   Press Tab
7.   Type "circle"
8.   Press the down arrow
9.   Press Enter
10. Attempt to click the output port of the "radius" node (this does not seem to work as expected)
11. Message box now says "Connecting the nodes. Please wait..."
12. The circle node created in steps 7 through 9 no longer exists.

![lunastudioissue](https://user-images.githubusercontent.com/1753801/35112917-e2eb611c-fc3c-11e7-9629-79ae70524960.png)

**Comment by kustosz** [comment]
@MCluck90 this should be fixed by the 1.1 release. Please download the installer anew and install the 1.1 version.
