### ISSUE TITLE
Symbol Resolution Error When Reusing Symbol

### ISSUE THREAD

**Issue by KyleHerndon** [luna/luna#94]
Ex1
```
def main:
    fiat = "USD"
    crypto = "BTC"
    prices = every 1.seconds (getCurrencyPrice crypto fiat)
    crypto = "ETH"
    prices = every 1.seconds (getCurrencyPrice crypto fiat)
    None
```

swapped to

Ex2
```
def main:
    fiat = "USD"
    cryptoBTC = "BTC"
    prices = every 1.seconds (getCurrencyPrice cryptoBTC fiat)
    cryptoETH = "ETH"
    prices = every 1.seconds (getCurrencyPrice cryptoETH fiat)
    None
```

and then back to Ex1 causes the `crypto` visual node to be combined into a single one, however it still acts like two separate nodes if you switching it again back to Ex2. For text/visual consistency probably requires that no symbols get renamed.

**Comment by piotrMocz** [comment]
This is interesting and I'm not 100% sure what is the right behaviour here. Maybe @mikusp or @wdanilo do ;)

I can confirm that there is a problem here and after pasting the two lines the graph/code looks like this:

![screen shot 2018-10-08 at 14 37 15](https://user-images.githubusercontent.com/3109645/46609330-d5625100-cb07-11e8-9160-d5883ea7a65f.png)

I think given that there was some work done in the symbol-duplication department, this can move to Backlog.
