### ISSUE TITLE
Luna on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [luna/luna#97]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of open source and software development since '09.)_

Luna looks _super cool_. Nice work!

We'd love to have you on the show sometime soon. Who would be best person to join us to talk about Luna and all the cool stuff y'all are up to?

Please email editors@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by wdanilo** [comment]
@jerodsanto please email us at contact@luna-lang.org. Thank you for your proposition, however, it should not be posted as github issue. Closing.
